language: node_js
sudo: false
node_js:
  - stable
  - '0.12'
  - '0.10'
before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
env:
  global:
  - USE_CLOUD=false
  - secure: wM1vqH3YzYjqGklgBPrEF8p5LZ0crRs6kZ32rtwy18m6q0nc0BbNoCT3rHPIXDUL9uhfA4OiKapniJIolm6bmsvxg37NI869yp7Z8Gv0OaBzF7/Qgl2Vkfzf3l8o+uW9Mw6WJrwgxYaxZmqIZdQ9RW9GgiJ/v03r4BsZoHcGkbk=
  - secure: hXekXwRhqvB1jTMeTuwY7S67FDObx0P+V5+6XAgtApwonD4phP+eswdnH58j8nMn6LgrSs2XZV6oekhx/OIiI2ZRWx0fq5XbefEu6AEC93UvwG6XFpDLT2NV2TquMJMiW7tlh8u0hV0CWgFtyLy/FWsmQ11ydhczfutcFVYCvHo=
matrix:
  include:
    - node_js: stable
      env: USE_CLOUD=true
  allow_failures:
    - env: USE_CLOUD=true
script:
  - npm test
